version: "3"

services:
  webserver:
    container_name: "${DOCKER_PREFIX}_webserver"
    image: nginx:alpine
    depends_on:
      - app
      - db
    restart: always
    tty: true
    ports:
      - "${DOCKER_HTTP_PORT}:80"
      - "${DOCKER_HTTPS_PORT}:443"
    volumes:
      - ./:/var/www/html
      - ./docker-files/docker/nginx/resources/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network
  app:
    container_name: "${DOCKER_PREFIX}_app"
    build: ./docker-files/docker/php
    restart: always
    tty: true
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
  db:
    container_name: "${DOCKER_PREFIX}_db"
    image: percona:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT}
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
      MYSQL_USER: ${DOCKER_DB_USER}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
    restart: always
    tty: true
    volumes:
      - ./docker-files/storage/percona:/var/lib/mysql/
      - ./docker-files/docker/percona/resources/my.cnf:/etc/my.cnf.d/my.cnf
    ports:
      - "${DOCKER_DB_EXTERNAL_PORT}:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: ${DOCKER_NETWORKS_DRIVER}
